export const TOUR_STEP_IDS = {
  SIDEBAR_NEW_TRAVEL: 'sidebar-new-travel',
  SIDEBAR_HOME: 'sidebar-home',
  SIDEBAR_PROFILE: 'sidebar-profile',
  SIDEBAR_ACCOUNT: 'sidebar-account',
  NAVBAR_NEW_TRAVEL: 'navbar-new-travel',
  NAVBAR_HOME: 'navbar-home',
  NAVBAR_PROFILE: 'navbar-profile',
  TRAVEL_FORM_ORIGIN: 'travel-form-origin',
  TRAVEL_FORM_DESTINATION: 'travel-form-destination',
  TRAVEL_FORM_DATE: 'travel-form-date',
  TRAVEL_FORM_TIME: 'travel-form-time',
  TRAVEL_FORM_SEATS: 'travel-form-seats',
  TRAVEL_FORM_PUBLISH: 'travel-form-publish',
  TRAVEL_FORM_ORIGIN_MAP: 'travel-form-origin-map',
  TRAVEL_FORM_DESTINATION_MAP: 'travel-form-destination-map',
  TRAVEL_FORM_DATE_INPUT: 'travel-form-date-input',
  TRAVEL_FORM_TIME_INPUT: 'travel-form-time-input',
  TRAVEL_FORM_SEATS_MINUS: 'travel-form-seats-minus',
  TRAVEL_FORM_SEATS_PLUS: 'travel-form-seats-plus',
  TRAVEL_FORM_PUBLISH_BUTTON: 'travel-form-publish-button',
  VEHICLE_FORM_COLOR: 'vehicle-form-color',
  VEHICLE_FORM_PLATE: 'vehicle-form-plate',
  VEHICLE_FORM_SEATS: 'vehicle-form-seats',
  VEHICLE_FORM_PRICE: 'vehicle-form-price',
  VEHICLE_FORM_ROUTE: 'vehicle-form-route',
  VEHICLE_FORM_SAVE: 'vehicle-form-save',
  ROLE_SELECTOR_OFFER: 'role-selector-offer',
  DIALOG_DRIVER: 'dialog-driver',
  DIALOG_DRIVER_SUBMIT: 'dialog-driver-submit',
  DIALOG_DRIVER_CONFIRMATION: 'dialog-driver-confirmation',
  OFFER_FORM_ROUTE: 'offer-form-route',
  OFFER_FORM_CONTRIBUTION: 'offer-form-contribution',
} as const;

export const ONBOARDING_WELCOME_KEY = 'carpool_onboarding_seen';
