/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as HealthcheckRouteImport } from './routes/healthcheck'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutAuthRouteImport } from './routes/_layout/_auth'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth.callback'
import { Route as LayoutAuthHomeRouteImport } from './routes/_layout/_auth/home'
import { Route as LayoutAuthProfileIndexRouteImport } from './routes/_layout/_auth/profile/index'
import { Route as ApiTravelIdOgRouteImport } from './routes/api/travel.$id.og'
import { Route as LayoutPublicTravelIdRouteImport } from './routes/_layout/_public/travel.$id'
import { Route as LayoutAuthTravelNewRouteImport } from './routes/_layout/_auth/travel/new'
import { Route as LayoutAuthProfileVehicleRouteImport } from './routes/_layout/_auth/profile/vehicle'
import { Route as LayoutAuthProfilePaymentsRouteImport } from './routes/_layout/_auth/profile/payments'
import { Route as LayoutAuthProfileLocationsRouteImport } from './routes/_layout/_auth/profile/locations'
import { Route as LayoutAuthProfileAsisstanceRouteImport } from './routes/_layout/_auth/profile/asisstance'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcheckRoute = HealthcheckRouteImport.update({
  id: '/healthcheck',
  path: '/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthHomeRoute = LayoutAuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthProfileIndexRoute = LayoutAuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const ApiTravelIdOgRoute = ApiTravelIdOgRouteImport.update({
  id: '/api/travel/$id/og',
  path: '/api/travel/$id/og',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicTravelIdRoute = LayoutPublicTravelIdRouteImport.update({
  id: '/_public/travel/$id',
  path: '/travel/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthTravelNewRoute = LayoutAuthTravelNewRouteImport.update({
  id: '/travel/new',
  path: '/travel/new',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthProfileVehicleRoute =
  LayoutAuthProfileVehicleRouteImport.update({
    id: '/profile/vehicle',
    path: '/profile/vehicle',
    getParentRoute: () => LayoutAuthRoute,
  } as any)
const LayoutAuthProfilePaymentsRoute =
  LayoutAuthProfilePaymentsRouteImport.update({
    id: '/profile/payments',
    path: '/profile/payments',
    getParentRoute: () => LayoutAuthRoute,
  } as any)
const LayoutAuthProfileLocationsRoute =
  LayoutAuthProfileLocationsRouteImport.update({
    id: '/profile/locations',
    path: '/profile/locations',
    getParentRoute: () => LayoutAuthRoute,
  } as any)
const LayoutAuthProfileAsisstanceRoute =
  LayoutAuthProfileAsisstanceRouteImport.update({
    id: '/profile/asisstance',
    path: '/profile/asisstance',
    getParentRoute: () => LayoutAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthcheck': typeof HealthcheckRoute
  '/sign-in': typeof SignInRoute
  '/home': typeof LayoutAuthHomeRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/profile/asisstance': typeof LayoutAuthProfileAsisstanceRoute
  '/profile/locations': typeof LayoutAuthProfileLocationsRoute
  '/profile/payments': typeof LayoutAuthProfilePaymentsRoute
  '/profile/vehicle': typeof LayoutAuthProfileVehicleRoute
  '/travel/new': typeof LayoutAuthTravelNewRoute
  '/travel/$id': typeof LayoutPublicTravelIdRoute
  '/api/travel/$id/og': typeof ApiTravelIdOgRoute
  '/profile': typeof LayoutAuthProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthcheck': typeof HealthcheckRoute
  '/sign-in': typeof SignInRoute
  '/home': typeof LayoutAuthHomeRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/profile/asisstance': typeof LayoutAuthProfileAsisstanceRoute
  '/profile/locations': typeof LayoutAuthProfileLocationsRoute
  '/profile/payments': typeof LayoutAuthProfilePaymentsRoute
  '/profile/vehicle': typeof LayoutAuthProfileVehicleRoute
  '/travel/new': typeof LayoutAuthTravelNewRoute
  '/travel/$id': typeof LayoutPublicTravelIdRoute
  '/api/travel/$id/og': typeof ApiTravelIdOgRoute
  '/profile': typeof LayoutAuthProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/healthcheck': typeof HealthcheckRoute
  '/sign-in': typeof SignInRoute
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren
  '/_layout/_auth/home': typeof LayoutAuthHomeRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_layout/_auth/profile/asisstance': typeof LayoutAuthProfileAsisstanceRoute
  '/_layout/_auth/profile/locations': typeof LayoutAuthProfileLocationsRoute
  '/_layout/_auth/profile/payments': typeof LayoutAuthProfilePaymentsRoute
  '/_layout/_auth/profile/vehicle': typeof LayoutAuthProfileVehicleRoute
  '/_layout/_auth/travel/new': typeof LayoutAuthTravelNewRoute
  '/_layout/_public/travel/$id': typeof LayoutPublicTravelIdRoute
  '/api/travel/$id/og': typeof ApiTravelIdOgRoute
  '/_layout/_auth/profile/': typeof LayoutAuthProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthcheck'
    | '/sign-in'
    | '/home'
    | '/api/auth/callback'
    | '/profile/asisstance'
    | '/profile/locations'
    | '/profile/payments'
    | '/profile/vehicle'
    | '/travel/new'
    | '/travel/$id'
    | '/api/travel/$id/og'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthcheck'
    | '/sign-in'
    | '/home'
    | '/api/auth/callback'
    | '/profile/asisstance'
    | '/profile/locations'
    | '/profile/payments'
    | '/profile/vehicle'
    | '/travel/new'
    | '/travel/$id'
    | '/api/travel/$id/og'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/healthcheck'
    | '/sign-in'
    | '/_layout/_auth'
    | '/_layout/_auth/home'
    | '/api/auth/callback'
    | '/_layout/_auth/profile/asisstance'
    | '/_layout/_auth/profile/locations'
    | '/_layout/_auth/profile/payments'
    | '/_layout/_auth/profile/vehicle'
    | '/_layout/_auth/travel/new'
    | '/_layout/_public/travel/$id'
    | '/api/travel/$id/og'
    | '/_layout/_auth/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  HealthcheckRoute: typeof HealthcheckRoute
  SignInRoute: typeof SignInRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiTravelIdOgRoute: typeof ApiTravelIdOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcheck': {
      id: '/healthcheck'
      path: '/healthcheck'
      fullPath: '/healthcheck'
      preLoaderRoute: typeof HealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_auth/home': {
      id: '/_layout/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthHomeRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/profile/': {
      id: '/_layout/_auth/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthProfileIndexRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/api/travel/$id/og': {
      id: '/api/travel/$id/og'
      path: '/api/travel/$id/og'
      fullPath: '/api/travel/$id/og'
      preLoaderRoute: typeof ApiTravelIdOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_public/travel/$id': {
      id: '/_layout/_public/travel/$id'
      path: '/travel/$id'
      fullPath: '/travel/$id'
      preLoaderRoute: typeof LayoutPublicTravelIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth/travel/new': {
      id: '/_layout/_auth/travel/new'
      path: '/travel/new'
      fullPath: '/travel/new'
      preLoaderRoute: typeof LayoutAuthTravelNewRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/profile/vehicle': {
      id: '/_layout/_auth/profile/vehicle'
      path: '/profile/vehicle'
      fullPath: '/profile/vehicle'
      preLoaderRoute: typeof LayoutAuthProfileVehicleRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/profile/payments': {
      id: '/_layout/_auth/profile/payments'
      path: '/profile/payments'
      fullPath: '/profile/payments'
      preLoaderRoute: typeof LayoutAuthProfilePaymentsRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/profile/locations': {
      id: '/_layout/_auth/profile/locations'
      path: '/profile/locations'
      fullPath: '/profile/locations'
      preLoaderRoute: typeof LayoutAuthProfileLocationsRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/profile/asisstance': {
      id: '/_layout/_auth/profile/asisstance'
      path: '/profile/asisstance'
      fullPath: '/profile/asisstance'
      preLoaderRoute: typeof LayoutAuthProfileAsisstanceRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
  }
}

interface LayoutAuthRouteChildren {
  LayoutAuthHomeRoute: typeof LayoutAuthHomeRoute
  LayoutAuthProfileAsisstanceRoute: typeof LayoutAuthProfileAsisstanceRoute
  LayoutAuthProfileLocationsRoute: typeof LayoutAuthProfileLocationsRoute
  LayoutAuthProfilePaymentsRoute: typeof LayoutAuthProfilePaymentsRoute
  LayoutAuthProfileVehicleRoute: typeof LayoutAuthProfileVehicleRoute
  LayoutAuthTravelNewRoute: typeof LayoutAuthTravelNewRoute
  LayoutAuthProfileIndexRoute: typeof LayoutAuthProfileIndexRoute
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthHomeRoute: LayoutAuthHomeRoute,
  LayoutAuthProfileAsisstanceRoute: LayoutAuthProfileAsisstanceRoute,
  LayoutAuthProfileLocationsRoute: LayoutAuthProfileLocationsRoute,
  LayoutAuthProfilePaymentsRoute: LayoutAuthProfilePaymentsRoute,
  LayoutAuthProfileVehicleRoute: LayoutAuthProfileVehicleRoute,
  LayoutAuthTravelNewRoute: LayoutAuthTravelNewRoute,
  LayoutAuthProfileIndexRoute: LayoutAuthProfileIndexRoute,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
  LayoutPublicTravelIdRoute: typeof LayoutPublicTravelIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutPublicTravelIdRoute: LayoutPublicTravelIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  HealthcheckRoute: HealthcheckRoute,
  SignInRoute: SignInRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiTravelIdOgRoute: ApiTravelIdOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
